### PR TITLE
Make slimline modular

### PR DESCRIPTION
**Pull request by mengelbrecht**
This PR implements #15 and more.

- [x] Use zsh-async for async functionality
- [x] Refactor code into sections
- [x] Add support for specifying the used sections and their order
- [x] Add formatting support for each section
- [x] Add fallback support for slimline v1 options
- [x] Update screenshots
- [x] Add support for custom user sections
- [x] Improve the code further
- [x] Add more sections?
- [x] Test the new code
- [x] Write documentation

### CODE REVIEW

**Comment by ghost** [comment]
Seems like https://github.com/mgee/slimline/issues/9 is resurfacing on develop branch again.

**Comment by mengelbrecht** [comment]
@katsika I cannot reproduce the issue you are experiencing. I tried fzf-marks and switched directories using `jump` several times. The git information was always accurate. Maybe it is a timing issue?

**Comment by ghost** [comment]
Ah, fixed it by calling all widgets from `$precmd_functions`, as they have done in urbainvaes/fzf-marks.

There is one thing though. nodejs section is not cleared when jumped out of directory containing package.json (not sure if it should be).

**Comment by mengelbrecht** [comment]
@katsika The issue with the nodejs section should be now fixed. Can you test it with the latest changes from the develop branch?

**Comment by ghost** [comment]
Ah, thanks. Seems alright now.

**Comment by ghost** [comment]
https://github.com/mgee/slimline/pull/16/commits/f460bacc7b9f9749d9209c716edb7febbf6b8c8e#diff-04c6e90faac2675aa89e2176d2eec7d8L238

vi-mode is missing from defaults in SLIMLINE_RIGHT_PROMPT_SECTIONS.

**Comment by mengelbrecht** [comment]
@katsika Good catch. Thanks!

**Pull request merged**
